### ISSUE TITLE
Problem with payment method

### ISSUE THREAD

**Issue by ColonelMoutarde** [paypal/PayPal-PHP-SDK#226]
Hello,
Only "paypal" is accepted for payment method, all other is unsupported ("credit_card").

**Comment by ColonelMoutarde** [comment]
the sentence is false :

For credit_card payment method, the supported funding instrument is credit_card or cardit_card_token

"cardit_card_token" for "credit_card_token".

```object(stdClass)[42]
  public 'name' => string 'VALIDATION_ERROR' (length=16)
  public 'details' => 
    array (size=1)
      0 => 
        object(stdClass)[39]
          public 'field' => string 'payer' (length=5)
          public 'issue' => string 'For credit_card payment method, the supported funding instrument is credit_card or cardit_card_token ' (length=101)
  public 'message' => string 'Invalid request - see details' (length=29)
  public 'information_link' => string 'https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR' (length=73)
  public 'debug_id' => string '8ac98b0755636' (length=13)
```

**Comment by jaypatel512** [comment]
Hey @ColonelMoutarde ! Can you please let me know where the statement is mentioned, is false ? I am not sure you meant the text is present in SDK or Developer Docs. 

Thanks.

**Comment by ColonelMoutarde** [comment]
"cardit_card_token" is the response from paypal server.

**Comment by ColonelMoutarde** [comment]
"credit_card" and others is presented in Payer class line 22
```php
/**
     * Payment method being used - PayPal Wallet payment, Bank Direct Debit, or Direct Credit card.
     * Valid Values: ["credit_card", "bank", "paypal"]
     *
     * @param string $payment_method
     * 
     * @return $this
     */
```

**Comment by jaypatel512** [comment]
I am not 100% sure if I got your question though. however, it is possible to create a payment using credit card information, as shown [here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/paypal/PayPal-PHP-SDK/master/sample/doc/payments/CreatePayment.html)

If your payment_method is set to :+1: 
1. paypal : You cannot pass any funding instrument, as it is not required.
2. credit_card: you can pass a new [credit card](http://htmlpreview.github.io/?https://raw.githubusercontent.com/paypal/PayPal-PHP-SDK/master/sample/doc/payments/CreatePayment.html) or [credit card token](http://htmlpreview.github.io/?https://raw.githubusercontent.com/paypal/PayPal-PHP-SDK/master/sample/doc/payments/CreatePaymentUsingSavedCard.html)

**Comment by ColonelMoutarde** [comment]
ok thanks

**Comment by jaypatel512** [comment]
Thanks @ColonelMoutarde for pointing this out. This change should fix this. I will be making release a bit later, so please if you want a temporary fix, feel free to make that small change to PayPalModel class manually. It should get updated nicely, the next time you update your SDK.

Thanks.

**Comment by almahmeed** [comment]
Good Morning All,

This post seems to be 2 years old, but it is exactly what I am facing right now.

When I set the setPaymentMethod to "credit_card", I receive an error.
I have changed the line in the payer class to set it explicitly to "credit_card" but I am still facing the same issue.
```
class Payer extends PayPalModel
{
    /**
     * Payment method being used - PayPal Wallet payment, Bank Direct Debit  or Direct Credit card.
     * Valid Values: ["credit_card", "bank", "paypal", "pay_upon_invoice", "carrier", "alternate_payment"]
     *
     * @param string $payment_method
     * 
     * @return $this
     */
    public function setPaymentMethod($payment_method)
    {
        // $this->payment_method = $payment_method;
``        $this->payment_method = "credit_card";
        return $this;
    }
```
How do I go around this issue?

Thanking you,
Aziz

**Comment by pp-randy** [comment]
@almahmeed do you have a Live integration you are supporting?  If not, please see the readme https://github.com/paypal/PayPal-PHP-SDK#direct-credit-card-support.  If you are approved for live, please create a new issue and provide a paypal-debug-id if you have one or additional error logging.

**Comment by pp-randy** [comment]
Locking this thread, Direct Credit Card integrations are not supported for new integrations.  If you have an existing integration on live, please submit a new issue and provide the requested troubleshooting details in the issue form.
