### ISSUE TITLE
Webhooks: Got Http response code 500...

### ISSUE THREAD

**Issue by facefunk** [paypal/PayPal-PHP-SDK#389]
I can't get a working set-up to test webhooks in the sandbox using the PHP SDK. The webhooks set in the developer app view never fire. When using the webhooks simulator the request does reach my application but on calling WebhookEvent::validateAndGetReceivedEvent I get back:

Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/notifications/webhooks-events/...

I've even purchased an SSL certificate for my test server in case that was the problem but it hasn't made a difference.

Can anybody help, please?

**Comment by facefunk** [comment]
Paypal-Debug-Id: 32262ce250b7a

**Comment by jaypatel512** [comment]
Just to make sure, have you followed the documentation around Webhook Validation in PHP SDK: https://github.com/paypal/PayPal-PHP-SDK/wiki/Webhook-Validation

**Comment by vasujain** [comment]
Just to add : There are no Webhook Events generated for your application "andmeetings" . As @jaypatel512 suggested, pls check the documentation and update here if you still see the issue.

**Comment by jaypatel512** [comment]
Any updates on this @facefunk ?

**Comment by flashultra** [comment]
Same happened to me "Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-6W4482673W002281V-61985753LP2332451" . I  follow guide for Webhook-Validation . I'm using Webhooks simulator 
Part of event:

**Comment by jaypatel512** [comment]
Hey @flashultra ! 

Can you please follow the instructions here : https://github.com/paypal/PayPal-PHP-SDK/wiki/Webhook-Validation

**Comment by flashultra** [comment]
Done. Same error " Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-2WR32451HC0233532-67976317FL4543714" These are my steps:
  1) Create webhooks from https://developer.paypal.com/developer/applications  ( SANDBOX WEBHOOKS )
 2) Testing from https://developer.paypal.com/developer/webhooksSimulator/
 3) I recevied full body of the message and validate  with validateAndGetReceivedEvent. This is my code:
   $bodyReceived = file_get_contents('php://input');
	$sdkConfig = array(
		"mode" => "sandbox"
	);
	$apiContext = new ApiContext(new OAuthTokenCredential($clientID, $clientSecret));
	$apiContext->setConfig($sdkConfig);
	
	try {
     $output = WebhookEvent::validateAndGetReceivedEvent($bodyReceived, $apiContext);
	} catch (Exception $ex) {
		error_log("Error: ".$ex->getMessage()."\n");
		exit(1);
	}
Problem still exist ( http 500 ) . Hope so this help.

**Comment by jaypatel512** [comment]
Oh ok ! Let me first try to reproduce the issue. In the mean time, if you could pass the `debug_id` in that exception. You should be able to see that in the logs.

**Comment by jaypatel512** [comment]
Hey @flashultra ! 

I think i found the reason why it is failing for you. As mentioned in the above documentation, as we are using the alternate method to validate webhooks, we cannot use webhook simulator in the PHP SDK. As, PHP does not support chain validation, there is no way for us the directly validate the data. 

To verify it it works for us, these are the steps you need.

1. Create webhook as you did.
2. Make sure you have "Payment Sale Completed" enabled in that webhook.
3. Create a payment using PayPal as funding source, and complete the checkout flow. 
4. This will trigger the notification in few seconds, and send a webhook to your given URL.
5. You should receive a full body of the message (but in this case, a real one, not from a webhook simulator). This should work now.

**Comment by flashultra** [comment]
I select all event types ( including Payment sale completed ) and indeed trigger the notification , but now receive new error: 
 " Webhook Event Id provided in the data is incorrect. This could happen if anyone other than PayPal is faking the incoming webhook data " 
I'm still using my code which post above without change and event comes from Paypal with sure.

**Comment by jaypatel512** [comment]
Oh ok !! Can you make sure the clientId and secret you are using in both the cases, are the same ? This error shows when the ID is not associated with your account.

**Comment by flashultra** [comment]
Clientid and secret looks correct and I'm using then to create payment. As additional information event which came is  PAYMENT.SALE.PENDING and the header and body are:

Accept: */*
PAYPAL-TRANSMISSION-ID: 65fb8690-621b-11e5-b6a0-77339302725b
PAYPAL-TRANSMISSION-TIME: 2015-09-23T17:49:11Z
PAYPAL-TRANSMISSION-SIG: RdVo8HXnCq5fFJ7xXyx03E/cNIJlE3fSj1DV2vdHL8IW8EVYejYn9irOmKLbEMSJ9Gg3YDkH3WnWmAvqsMLEoVAJFTBQOm9LMuTibvgUMcoNMBR+ulyX0XaYXGFI1D933wwYKD+wRMSQE4hxtWkBq4Ep7Mb7Jb21tLYYyEGGATNlCHB/TXbVeOREBMhd9cycomo+EIH49ln11A4QxJVZSpsmNcgFj4QiadjXgb+8F5F7fUW6vy7xQ9VBAe4k1Vgmab7UFZ5QiGqJYbVSRVF5BJ0io3zesC8bsAh+a0vQKCjyUMvHyZWD7yAXzMCwXWlbEdQSx78iCiOndm44sPXsJw==
PAYPAL-AUTH-VERSION: v2
PAYPAL-CERT-URL: https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77
PAYPAL-AUTH-ALGO: SHA256withRSA
Content-Type: application/json
User-Agent: PayPal/AUHD-200.0-17861278
Host: fortegames.com
correlation-id: 576cdc028ed6c
Content-Length: 1290

{"id":"WH-0CL10860BH294794L-43053985L1678705N","create_time":"2015-09-23T17:49:11Z","resource_type":"sale","event_type":"PAYMENT.SALE.PENDING","summary":"Payment pending for EUR 4.0 EUR","resource":{"id":"73A89859TB8039106","create_time":"2015-09-23T17:47:59Z","update_time":"2015-09-23T17:48:45Z","amount":{"total":"4.00","currency":"EUR"},"payment_mode":"INSTANT_TRANSFER","state":"pending","reason_code":"RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION","protection_eligibility":"ELIGIBLE","protection_eligibility_type":"ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE","parent_payment":"PAY-4R882056D0107910PKYBOLTY","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/sale/73A89859TB8039106","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/sale/73A89859TB8039106/refund","rel":"refund","method":"POST"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-4R882056D0107910PKYBOLTY","rel":"parent_payment","method":"GET"}]},"links":[{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-0CL10860BH294794L-43053985L1678705N","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-0CL10860BH294794L-43053985L1678705N/resend","rel":"resend","method":"POST"}]}

**Comment by flashultra** [comment]
Is there any update ? I just test and the problem still exist.  For what I saw the error come from here:
 https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/WebhookEvent.php#L196

**Comment by kenjohnson** [comment]
@flashultra
   I have the same problem as you do
   I am using PHP-SDK 1.5.1
   I am paying by PayPal and using my shopping cart

**Comment by jaypatel512** [comment]
We had a similar issue on webhooks where they were getting 400 Exception on webhook validation. The temporary fix is described here: https://github.com/paypal/PayPal-PHP-SDK/issues/412

From what I can tell, the issue is a bit different in your case, but I would recommend updating to 1.6.0 as that also includes the other fix in webhooks API.

**Comment by facefunk** [comment]
This was my fault, I read the documentation but didn't fully understand the procedure. I've integrated with IPN before and I think I was expecting the REST integration to be more similar. The difference between the SDKs and the SSL and PHP issues all got tangled up in my head and I missed the fact that I wasn't executing the payment correctly, I was expecting to have to do it on a webhook instead. My mistake, sorry about that.
